

// TOOL:     vlog2tf
// DATE:     Fri Apr 12 15:54:29 2013
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   Booth_mult
// DESIGN:   Booth_mult
// FILENAME: Booth_mult_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ns / 100 ps

// Define Module for Test Fixture
module Booth_mult_tf();

// Inputs
    reg [17:0] mplier;
    reg [17:0] mcand;
    reg n_reset;
    reg start;
    reg clk;


// Outputs
    wire [35:0] product;
    wire done;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    Booth_mult UUT (
        .product(product), 
        .done(done), 
        .mplier(mplier), 
        .mcand(mcand), 
        .n_reset(n_reset), 
        .start(start), 
        .clk(clk)
        );
initial begin
	$dumpfile("test.vcd");
	$dumpvars(0,Booth_mult_tf);
end

// Initialize Inputs
// You can add your stimulus here
    initial begin
            mplier = 0;
            mcand = 0;
            n_reset = 0;
            start = 0;
            clk = 0;
    end

	always
		#20 clk = ~clk;
		
	always
		begin
/////// 18 bit test

			#40		
				n_reset = 1'b 1;
			#40	
				mcand = 18'b 001001100011001001;
				mplier = 18'b 000110001011011010;
			#40
				start = 1'b 1;
			#40
				start = 1'b 0;				
			
			#400	
				mcand = 18'b 010011010001000011;
				mplier = 18'b 100110100010001011;
			#40
				start = 1'b 1;
			#40
				start = 1'b 0;		
				
			#400	
				mcand = 18'b 011101101001100011;
				mplier = 18'b 010011000111110110;
			#40
				start = 1'b 1;
			#40
				start = 1'b 0;		
				
				
			#400	
				mcand = 18'b 110011000101101111;
				mplier = 18'b 101101011001100011;
			#40
				start = 1'b 1;
			#40
				start = 1'b 0;		

			#400	
				mcand = 18'b 101010111011101101;
				mplier = 18'b 101101011111010111;
			#40
				start = 1'b 1;
			#40
				start = 1'b 0;		

			#400	
				mcand = 18'b 010110011111011111;
				mplier = 18'b 100010111111011101;
			#40
				start = 1'b 1;
			#40
				start = 1'b 0;		
				
			#400	
				mcand = 18'b 000111010101111110;
				mplier = 18'b 101011111010111110;
			#40
				start = 1'b 1;
			#40
				start = 1'b 0;		
				
				
			#400	
				mcand = 18'b 111101100010111110;
				mplier = 18'b 010111110011000011;
			#40
				start = 1'b 1;
			#40
				start = 1'b 0;		

			#400	
				mcand = 18'b 010110110101111101;
				mplier = 18'b 011110010111110011;
			#40
				start = 1'b 1;
			#40
				start = 1'b 0;		

		end
endmodule // Booth_mult_tf
